# Production runtime
# Google Cloud Run will inject a $PORT env variable which will be consumed by Astro during runtime. Ex. ENV PORT 8080

FROM node:alpine3.16 as node
FROM node as builder

RUN mkdir -p /usr/src/blog

# Copy common files
WORKDIR /usr/src
COPY ./common ./common

WORKDIR /usr/src/blog

# Copy source files
COPY ./blog ./
# Install dependencies
RUN npm ci --only=prod

# Build app
RUN npm run build

# Start app 
CMD npm run start