# Deploy admin when merge

name: Deploy to Firebase Hosting on Merge or Dispatch
"on":
  push:
    branches:
      - main
    paths:
      - admin/**
      - common/**
  workflow_dispatch:
    inputs:
      note:
        description: "Enter a short name"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js and Setup Cache
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: admin/package-lock.json

      - name: Install dependencies
          working-directory: admin/
          run: |
            npm ci --prefer-offline --only=prod
            npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TAKEMETHERE_365622 }}"
          channelId: live
          projectId: takemethere-365622
