# .github/workflows/gcr-cleaner.yml
# Referenced: https://github.com/GoogleCloudPlatform/gcr-cleaner

name: "GCR Cleaner"

on:
  schedule:
    - cron: "0 0 * * 0" # runs weekly
  workflow_dispatch:

jobs:
  gcr-cleaner:
    runs-on: "ubuntu-latest"
    steps:
      - name: Login to GAR
        uses: docker/login-action@v2
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      # customize based on the gcr-cleaner flags
      - uses: "docker://us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli"
        with:
          args: >-
            -repo=us.gcr.io/takemethere-365622/takemethere-mono
            -recursive
            -grace=48h
